### ISSUE TITLE
How to save log to log file in production mode?

### ISSUE THREAD

**Issue by adityarizkyramadhan** [SulthanAbiyyu/dflogger#3]

**Comment by SulthanAbiyyu** [comment]
Since dflogger is based on pandas dataframe, you can save to any format that is supported by pandas.  In their [documentation](https://pandas.pydata.org/docs), I don't see a log file supported since it's not practical to save a table in a log file. To be clear, dflogger is meant for logging or tracking machine learning experiments. You can track the hyperparameter used and the metric score. Hope this helps
